use roommate;
truncate table city;

insert into city (city_ID, zip, city_name, state) values (1, '64504', 'Saint Joseph', 'MO');
insert into city (city_ID, zip, city_name, state) values (2, '99709', 'Fairbanks', 'AK');
insert into city (city_ID, zip, city_name, state) values (3, '91205', 'Glendale', 'CA');
insert into city (city_ID, zip, city_name, state) values (4, '97232', 'Portland', 'OR');
insert into city (city_ID, zip, city_name, state) values (5, '60681', 'Chicago', 'IL');
insert into city (city_ID, zip, city_name, state) values (6, '33013', 'Hialeah', 'FL');
insert into city (city_ID, zip, city_name, state) values (7, '46406', 'Gary', 'IN');
insert into city (city_ID, zip, city_name, state) values (8, '40596', 'Lexington', 'KY');
insert into city (city_ID, zip, city_name, state) values (9, '22908', 'Charlottesville', 'VA');
insert into city (city_ID, zip, city_name, state) values (10, '92410', 'San Bernardino', 'CA');
insert into city (city_ID, zip, city_name, state) values (11, '45403', 'Dayton', 'OH');
insert into city (city_ID, zip, city_name, state) values (12, '48242', 'Detroit', 'MI');
insert into city (city_ID, zip, city_name, state) values (13, '61614', 'Peoria', 'IL');
insert into city (city_ID, zip, city_name, state) values (14, '68164', 'Omaha', 'NE');
insert into city (city_ID, zip, city_name, state) values (15, '28405', 'Wilmington', 'NC');
insert into city (city_ID, zip, city_name, state) values (16, '46805', 'Fort Wayne', 'IN');
insert into city (city_ID, zip, city_name, state) values (17, '32854', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (18, '34665', 'Pinellas Park', 'FL');
insert into city (city_ID, zip, city_name, state) values (19, '70820', 'Baton Rouge', 'LA');
insert into city (city_ID, zip, city_name, state) values (20, '90071', 'Los Angeles', 'CA');
insert into city (city_ID, zip, city_name, state) values (21, '70160', 'New Orleans', 'LA');
insert into city (city_ID, zip, city_name, state) values (22, '06127', 'West Hartford', 'CT');
insert into city (city_ID, zip, city_name, state) values (23, '08638', 'Trenton', 'NJ');
insert into city (city_ID, zip, city_name, state) values (24, '10131', 'New York City', 'NY');
insert into city (city_ID, zip, city_name, state) values (25, '78235', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (26, '20073', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (27, '80217', 'Denver', 'CO');
insert into city (city_ID, zip, city_name, state) values (28, '20244', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (29, '12262', 'Albany', 'NY');
insert into city (city_ID, zip, city_name, state) values (30, '23277', 'Richmond', 'VA');
insert into city (city_ID, zip, city_name, state) values (31, '34290', 'North Port', 'FL');
insert into city (city_ID, zip, city_name, state) values (32, '32309', 'Tallahassee', 'FL');
insert into city (city_ID, zip, city_name, state) values (33, '10633', 'White Plains', 'NY');
insert into city (city_ID, zip, city_name, state) values (34, '20167', 'Sterling', 'VA');
insert into city (city_ID, zip, city_name, state) values (35, '46620', 'South Bend', 'IN');
insert into city (city_ID, zip, city_name, state) values (36, '19131', 'Philadelphia', 'PA');
insert into city (city_ID, zip, city_name, state) values (37, '23289', 'Richmond', 'VA');
insert into city (city_ID, zip, city_name, state) values (38, '21281', 'Baltimore', 'MD');
insert into city (city_ID, zip, city_name, state) values (39, '75205', 'Dallas', 'TX');
insert into city (city_ID, zip, city_name, state) values (40, '87180', 'Albuquerque', 'NM');
insert into city (city_ID, zip, city_name, state) values (41, '63143', 'Saint Louis', 'MO');
insert into city (city_ID, zip, city_name, state) values (42, '48092', 'Warren', 'MI');
insert into city (city_ID, zip, city_name, state) values (43, '78415', 'Corpus Christi', 'TX');
insert into city (city_ID, zip, city_name, state) values (44, '77554', 'Galveston', 'TX');
insert into city (city_ID, zip, city_name, state) values (45, '33705', 'Saint Petersburg', 'FL');
insert into city (city_ID, zip, city_name, state) values (46, '76115', 'Fort Worth', 'TX');
insert into city (city_ID, zip, city_name, state) values (47, '91913', 'Chula Vista', 'CA');
insert into city (city_ID, zip, city_name, state) values (48, '55146', 'Saint Paul', 'MN');
insert into city (city_ID, zip, city_name, state) values (49, '32808', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (50, '66699', 'Topeka', 'KS');
insert into city (city_ID, zip, city_name, state) values (51, '32215', 'Jacksonville', 'FL');
insert into city (city_ID, zip, city_name, state) values (52, '44125', 'Cleveland', 'OH');
insert into city (city_ID, zip, city_name, state) values (53, '32941', 'Melbourne', 'FL');
insert into city (city_ID, zip, city_name, state) values (54, '61105', 'Rockford', 'IL');
insert into city (city_ID, zip, city_name, state) values (55, '15286', 'Pittsburgh', 'PA');
insert into city (city_ID, zip, city_name, state) values (56, '99599', 'Anchorage', 'AK');
insert into city (city_ID, zip, city_name, state) values (57, '20591', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (58, '81010', 'Pueblo', 'CO');
insert into city (city_ID, zip, city_name, state) values (59, '50315', 'Des Moines', 'IA');
insert into city (city_ID, zip, city_name, state) values (60, '21275', 'Baltimore', 'MD');
insert into city (city_ID, zip, city_name, state) values (61, '78296', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (62, '76310', 'Wichita Falls', 'TX');
insert into city (city_ID, zip, city_name, state) values (63, '44305', 'Akron', 'OH');
insert into city (city_ID, zip, city_name, state) values (64, '30089', 'Decatur', 'GA');
insert into city (city_ID, zip, city_name, state) values (65, '74170', 'Tulsa', 'OK');
insert into city (city_ID, zip, city_name, state) values (66, '93106', 'Santa Barbara', 'CA');
insert into city (city_ID, zip, city_name, state) values (67, '29416', 'Charleston', 'SC');
insert into city (city_ID, zip, city_name, state) values (68, '44197', 'Cleveland', 'OH');
insert into city (city_ID, zip, city_name, state) values (69, '32590', 'Pensacola', 'FL');
insert into city (city_ID, zip, city_name, state) values (70, '60567', 'Naperville', 'IL');
insert into city (city_ID, zip, city_name, state) values (71, '92165', 'San Diego', 'CA');
insert into city (city_ID, zip, city_name, state) values (72, '68117', 'Omaha', 'NE');
insert into city (city_ID, zip, city_name, state) values (73, '17405', 'York', 'PA');
insert into city (city_ID, zip, city_name, state) values (74, '50393', 'Des Moines', 'IA');
insert into city (city_ID, zip, city_name, state) values (75, '45264', 'Cincinnati', 'OH');
insert into city (city_ID, zip, city_name, state) values (76, '33694', 'Tampa', 'FL');
insert into city (city_ID, zip, city_name, state) values (77, '20535', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (78, '85077', 'Phoenix', 'AZ');
insert into city (city_ID, zip, city_name, state) values (79, '37235', 'Nashville', 'TN');
insert into city (city_ID, zip, city_name, state) values (80, '48901', 'Lansing', 'MI');
insert into city (city_ID, zip, city_name, state) values (81, '43268', 'Columbus', 'OH');
insert into city (city_ID, zip, city_name, state) values (82, '34629', 'Clearwater', 'FL');
insert into city (city_ID, zip, city_name, state) values (83, '77020', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (84, '32868', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (85, '93399', 'Bakersfield', 'CA');
insert into city (city_ID, zip, city_name, state) values (86, '17121', 'Harrisburg', 'PA');
insert into city (city_ID, zip, city_name, state) values (87, '90087', 'Los Angeles', 'CA');
insert into city (city_ID, zip, city_name, state) values (88, '22217', 'Arlington', 'VA');
insert into city (city_ID, zip, city_name, state) values (89, '33064', 'Pompano Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (90, '30316', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (91, '22903', 'Charlottesville', 'VA');
insert into city (city_ID, zip, city_name, state) values (92, '46867', 'Fort Wayne', 'IN');
insert into city (city_ID, zip, city_name, state) values (93, '14276', 'Buffalo', 'NY');
insert into city (city_ID, zip, city_name, state) values (94, '30356', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (95, '07310', 'Jersey City', 'NJ');
insert into city (city_ID, zip, city_name, state) values (96, '90310', 'Inglewood', 'CA');
insert into city (city_ID, zip, city_name, state) values (97, '34665', 'Pinellas Park', 'FL');
insert into city (city_ID, zip, city_name, state) values (98, '11210', 'Brooklyn', 'NY');
insert into city (city_ID, zip, city_name, state) values (99, '97211', 'Portland', 'OR');
insert into city (city_ID, zip, city_name, state) values (100, '80044', 'Aurora', 'CO');
insert into city (city_ID, zip, city_name, state) values (101, '19131', 'Philadelphia', 'PA');
insert into city (city_ID, zip, city_name, state) values (102, '48206', 'Detroit', 'MI');
insert into city (city_ID, zip, city_name, state) values (103, '73135', 'Oklahoma City', 'OK');
insert into city (city_ID, zip, city_name, state) values (104, '32813', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (105, '71115', 'Shreveport', 'LA');
insert into city (city_ID, zip, city_name, state) values (106, '44705', 'Canton', 'OH');
insert into city (city_ID, zip, city_name, state) values (107, '36670', 'Mobile', 'AL');
insert into city (city_ID, zip, city_name, state) values (108, '23324', 'Chesapeake', 'VA');
insert into city (city_ID, zip, city_name, state) values (109, '94142', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (110, '79159', 'Amarillo', 'TX');
insert into city (city_ID, zip, city_name, state) values (111, '46216', 'Indianapolis', 'IN');
insert into city (city_ID, zip, city_name, state) values (112, '68164', 'Omaha', 'NE');
insert into city (city_ID, zip, city_name, state) values (113, '59105', 'Billings', 'MT');
insert into city (city_ID, zip, city_name, state) values (114, '34102', 'Naples', 'FL');
insert into city (city_ID, zip, city_name, state) values (115, '56398', 'Saint Cloud', 'MN');
insert into city (city_ID, zip, city_name, state) values (116, '36125', 'Montgomery', 'AL');
insert into city (city_ID, zip, city_name, state) values (117, '77045', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (118, '56372', 'Saint Cloud', 'MN');
insert into city (city_ID, zip, city_name, state) values (119, '46614', 'South Bend', 'IN');
insert into city (city_ID, zip, city_name, state) values (120, '22212', 'Arlington', 'VA');
insert into city (city_ID, zip, city_name, state) values (121, '46862', 'Fort Wayne', 'IN');
insert into city (city_ID, zip, city_name, state) values (122, '78465', 'Corpus Christi', 'TX');
insert into city (city_ID, zip, city_name, state) values (123, '84145', 'Salt Lake City', 'UT');
insert into city (city_ID, zip, city_name, state) values (124, '32236', 'Jacksonville', 'FL');
insert into city (city_ID, zip, city_name, state) values (125, '30311', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (126, '48275', 'Detroit', 'MI');
insert into city (city_ID, zip, city_name, state) values (127, '92410', 'San Bernardino', 'CA');
insert into city (city_ID, zip, city_name, state) values (128, '78710', 'Austin', 'TX');
insert into city (city_ID, zip, city_name, state) values (129, '66112', 'Kansas City', 'KS');
insert into city (city_ID, zip, city_name, state) values (130, '46239', 'Indianapolis', 'IN');
insert into city (city_ID, zip, city_name, state) values (131, '76210', 'Denton', 'TX');
insert into city (city_ID, zip, city_name, state) values (132, '44720', 'Canton', 'OH');
insert into city (city_ID, zip, city_name, state) values (133, '20599', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (134, '32813', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (135, '92110', 'San Diego', 'CA');
insert into city (city_ID, zip, city_name, state) values (136, '37250', 'Nashville', 'TN');
insert into city (city_ID, zip, city_name, state) values (137, '33731', 'Saint Petersburg', 'FL');
insert into city (city_ID, zip, city_name, state) values (138, '76598', 'Gatesville', 'TX');
insert into city (city_ID, zip, city_name, state) values (139, '34643', 'Largo', 'FL');
insert into city (city_ID, zip, city_name, state) values (140, '94110', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (141, '06183', 'Hartford', 'CT');
insert into city (city_ID, zip, city_name, state) values (142, '06912', 'Stamford', 'CT');
insert into city (city_ID, zip, city_name, state) values (143, '99512', 'Anchorage', 'AK');
insert into city (city_ID, zip, city_name, state) values (144, '25711', 'Huntington', 'WV');
insert into city (city_ID, zip, city_name, state) values (145, '94207', 'Sacramento', 'CA');
insert into city (city_ID, zip, city_name, state) values (146, '99709', 'Fairbanks', 'AK');
insert into city (city_ID, zip, city_name, state) values (147, '95397', 'Modesto', 'CA');
insert into city (city_ID, zip, city_name, state) values (148, '23289', 'Richmond', 'VA');
insert into city (city_ID, zip, city_name, state) values (149, '60078', 'Palatine', 'IL');
insert into city (city_ID, zip, city_name, state) values (150, '37205', 'Nashville', 'TN');
insert into city (city_ID, zip, city_name, state) values (151, '64136', 'Kansas City', 'MO');
insert into city (city_ID, zip, city_name, state) values (152, '33715', 'Saint Petersburg', 'FL');
insert into city (city_ID, zip, city_name, state) values (153, '93709', 'Fresno', 'CA');
insert into city (city_ID, zip, city_name, state) values (154, '73104', 'Oklahoma City', 'OK');
insert into city (city_ID, zip, city_name, state) values (155, '94273', 'Sacramento', 'CA');
insert into city (city_ID, zip, city_name, state) values (156, '32399', 'Tallahassee', 'FL');
insert into city (city_ID, zip, city_name, state) values (157, '88558', 'El Paso', 'TX');
insert into city (city_ID, zip, city_name, state) values (158, '93094', 'Simi Valley', 'CA');
insert into city (city_ID, zip, city_name, state) values (159, '76016', 'Arlington', 'TX');
insert into city (city_ID, zip, city_name, state) values (160, '15205', 'Pittsburgh', 'PA');
insert into city (city_ID, zip, city_name, state) values (161, '77293', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (162, '94154', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (163, '64114', 'Kansas City', 'MO');
insert into city (city_ID, zip, city_name, state) values (164, '27635', 'Raleigh', 'NC');
insert into city (city_ID, zip, city_name, state) values (165, '66622', 'Topeka', 'KS');
insert into city (city_ID, zip, city_name, state) values (166, '20337', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (167, '27455', 'Greensboro', 'NC');
insert into city (city_ID, zip, city_name, state) values (168, '70129', 'New Orleans', 'LA');
insert into city (city_ID, zip, city_name, state) values (169, '19892', 'Wilmington', 'DE');
insert into city (city_ID, zip, city_name, state) values (170, '93311', 'Bakersfield', 'CA');
insert into city (city_ID, zip, city_name, state) values (171, '30605', 'Athens', 'GA');
insert into city (city_ID, zip, city_name, state) values (172, '74149', 'Tulsa', 'OK');
insert into city (city_ID, zip, city_name, state) values (173, '30392', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (174, '94126', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (175, '33233', 'Miami', 'FL');
insert into city (city_ID, zip, city_name, state) values (176, '60697', 'Chicago', 'IL');
insert into city (city_ID, zip, city_name, state) values (177, '90087', 'Los Angeles', 'CA');
insert into city (city_ID, zip, city_name, state) values (178, '11225', 'Brooklyn', 'NY');
insert into city (city_ID, zip, city_name, state) values (179, '70183', 'New Orleans', 'LA');
insert into city (city_ID, zip, city_name, state) values (180, '75044', 'Garland', 'TX');
insert into city (city_ID, zip, city_name, state) values (181, '77250', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (182, '12227', 'Albany', 'NY');
insert into city (city_ID, zip, city_name, state) values (183, '10474', 'Bronx', 'NY');
insert into city (city_ID, zip, city_name, state) values (184, '80161', 'Littleton', 'CO');
insert into city (city_ID, zip, city_name, state) values (185, '22070', 'Herndon', 'VA');
insert into city (city_ID, zip, city_name, state) values (186, '29403', 'Charleston', 'SC');
insert into city (city_ID, zip, city_name, state) values (187, '06120', 'Hartford', 'CT');
insert into city (city_ID, zip, city_name, state) values (188, '80005', 'Arvada', 'CO');
insert into city (city_ID, zip, city_name, state) values (189, '75037', 'Irving', 'TX');
insert into city (city_ID, zip, city_name, state) values (190, '20404', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (191, '38136', 'Memphis', 'TN');
insert into city (city_ID, zip, city_name, state) values (192, '39216', 'Jackson', 'MS');
insert into city (city_ID, zip, city_name, state) values (193, '89519', 'Reno', 'NV');
insert into city (city_ID, zip, city_name, state) values (194, '35805', 'Huntsville', 'AL');
insert into city (city_ID, zip, city_name, state) values (195, '32225', 'Jacksonville', 'FL');
insert into city (city_ID, zip, city_name, state) values (196, '61651', 'Peoria', 'IL');
insert into city (city_ID, zip, city_name, state) values (197, '29240', 'Columbia', 'SC');
insert into city (city_ID, zip, city_name, state) values (198, '36610', 'Mobile', 'AL');
insert into city (city_ID, zip, city_name, state) values (199, '87195', 'Albuquerque', 'NM');
insert into city (city_ID, zip, city_name, state) values (200, '20210', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (201, '90060', 'Los Angeles', 'CA');
insert into city (city_ID, zip, city_name, state) values (202, '92115', 'San Diego', 'CA');
insert into city (city_ID, zip, city_name, state) values (203, '98185', 'Seattle', 'WA');
insert into city (city_ID, zip, city_name, state) values (204, '16505', 'Erie', 'PA');
insert into city (city_ID, zip, city_name, state) values (205, '90101', 'Los Angeles', 'CA');
insert into city (city_ID, zip, city_name, state) values (206, '29416', 'Charleston', 'SC');
insert into city (city_ID, zip, city_name, state) values (207, '61110', 'Rockford', 'IL');
insert into city (city_ID, zip, city_name, state) values (208, '60674', 'Chicago', 'IL');
insert into city (city_ID, zip, city_name, state) values (209, '18706', 'Wilkes Barre', 'PA');
insert into city (city_ID, zip, city_name, state) values (210, '93094', 'Simi Valley', 'CA');
insert into city (city_ID, zip, city_name, state) values (211, '29305', 'Spartanburg', 'SC');
insert into city (city_ID, zip, city_name, state) values (212, '68164', 'Omaha', 'NE');
insert into city (city_ID, zip, city_name, state) values (213, '50305', 'Des Moines', 'IA');
insert into city (city_ID, zip, city_name, state) values (214, '14205', 'Buffalo', 'NY');
insert into city (city_ID, zip, city_name, state) values (215, '98158', 'Seattle', 'WA');
insert into city (city_ID, zip, city_name, state) values (216, '32803', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (217, '77276', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (218, '46825', 'Fort Wayne', 'IN');
insert into city (city_ID, zip, city_name, state) values (219, '34210', 'Bradenton', 'FL');
insert into city (city_ID, zip, city_name, state) values (220, '74126', 'Tulsa', 'OK');
insert into city (city_ID, zip, city_name, state) values (221, '98506', 'Olympia', 'WA');
insert into city (city_ID, zip, city_name, state) values (222, '13205', 'Syracuse', 'NY');
insert into city (city_ID, zip, city_name, state) values (223, '33421', 'West Palm Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (224, '88574', 'El Paso', 'TX');
insert into city (city_ID, zip, city_name, state) values (225, '43635', 'Toledo', 'OH');
insert into city (city_ID, zip, city_name, state) values (226, '28247', 'Charlotte', 'NC');
insert into city (city_ID, zip, city_name, state) values (227, '36628', 'Mobile', 'AL');
insert into city (city_ID, zip, city_name, state) values (228, '84170', 'Salt Lake City', 'UT');
insert into city (city_ID, zip, city_name, state) values (229, '01905', 'Lynn', 'MA');
insert into city (city_ID, zip, city_name, state) values (230, '99812', 'Juneau', 'AK');
insert into city (city_ID, zip, city_name, state) values (231, '52809', 'Davenport', 'IA');
insert into city (city_ID, zip, city_name, state) values (232, '80217', 'Denver', 'CO');
insert into city (city_ID, zip, city_name, state) values (233, '20268', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (234, '31136', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (235, '29203', 'Columbia', 'SC');
insert into city (city_ID, zip, city_name, state) values (236, '45807', 'Lima', 'OH');
insert into city (city_ID, zip, city_name, state) values (237, '94147', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (238, '54313', 'Green Bay', 'WI');
insert into city (city_ID, zip, city_name, state) values (239, '59112', 'Billings', 'MT');
insert into city (city_ID, zip, city_name, state) values (240, '08104', 'Camden', 'NJ');
insert into city (city_ID, zip, city_name, state) values (241, '16565', 'Erie', 'PA');
insert into city (city_ID, zip, city_name, state) values (242, '29605', 'Greenville', 'SC');
insert into city (city_ID, zip, city_name, state) values (243, '33075', 'Pompano Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (244, '31914', 'Columbus', 'GA');
insert into city (city_ID, zip, city_name, state) values (245, '66210', 'Shawnee Mission', 'KS');
insert into city (city_ID, zip, city_name, state) values (246, '70826', 'Baton Rouge', 'LA');
insert into city (city_ID, zip, city_name, state) values (247, '33164', 'Miami', 'FL');
insert into city (city_ID, zip, city_name, state) values (248, '19892', 'Wilmington', 'DE');
insert into city (city_ID, zip, city_name, state) values (249, '70142', 'New Orleans', 'LA');
insert into city (city_ID, zip, city_name, state) values (250, '29905', 'Beaufort', 'SC');
insert into city (city_ID, zip, city_name, state) values (251, '33405', 'West Palm Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (252, '92405', 'San Bernardino', 'CA');
insert into city (city_ID, zip, city_name, state) values (253, '29605', 'Greenville', 'SC');
insert into city (city_ID, zip, city_name, state) values (254, '60351', 'Carol Stream', 'IL');
insert into city (city_ID, zip, city_name, state) values (255, '33715', 'Saint Petersburg', 'FL');
insert into city (city_ID, zip, city_name, state) values (256, '33954', 'Port Charlotte', 'FL');
insert into city (city_ID, zip, city_name, state) values (257, '94089', 'Sunnyvale', 'CA');
insert into city (city_ID, zip, city_name, state) values (258, '73152', 'Oklahoma City', 'OK');
insert into city (city_ID, zip, city_name, state) values (259, '99210', 'Spokane', 'WA');
insert into city (city_ID, zip, city_name, state) values (260, '57193', 'Sioux Falls', 'SD');
insert into city (city_ID, zip, city_name, state) values (261, '17126', 'Harrisburg', 'PA');
insert into city (city_ID, zip, city_name, state) values (262, '93721', 'Fresno', 'CA');
insert into city (city_ID, zip, city_name, state) values (263, '19886', 'Wilmington', 'DE');
insert into city (city_ID, zip, city_name, state) values (264, '62756', 'Springfield', 'IL');
insert into city (city_ID, zip, city_name, state) values (265, '93111', 'Santa Barbara', 'CA');
insert into city (city_ID, zip, city_name, state) values (266, '21281', 'Baltimore', 'MD');
insert into city (city_ID, zip, city_name, state) values (267, '50706', 'Waterloo', 'IA');
insert into city (city_ID, zip, city_name, state) values (268, '43666', 'Toledo', 'OH');
insert into city (city_ID, zip, city_name, state) values (269, '40210', 'Louisville', 'KY');
insert into city (city_ID, zip, city_name, state) values (270, '89714', 'Carson City', 'NV');
insert into city (city_ID, zip, city_name, state) values (271, '89125', 'Las Vegas', 'NV');
insert into city (city_ID, zip, city_name, state) values (272, '79415', 'Lubbock', 'TX');
insert into city (city_ID, zip, city_name, state) values (273, '98498', 'Lakewood', 'WA');
insert into city (city_ID, zip, city_name, state) values (274, '84145', 'Salt Lake City', 'UT');
insert into city (city_ID, zip, city_name, state) values (275, '96845', 'Honolulu', 'HI');
insert into city (city_ID, zip, city_name, state) values (276, '20036', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (277, '27455', 'Greensboro', 'NC');
insert into city (city_ID, zip, city_name, state) values (278, '76505', 'Temple', 'TX');
insert into city (city_ID, zip, city_name, state) values (279, '10459', 'Bronx', 'NY');
insert into city (city_ID, zip, city_name, state) values (280, '89130', 'Las Vegas', 'NV');
insert into city (city_ID, zip, city_name, state) values (281, '28815', 'Asheville', 'NC');
insert into city (city_ID, zip, city_name, state) values (282, '56944', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (283, '89193', 'Las Vegas', 'NV');
insert into city (city_ID, zip, city_name, state) values (284, '78210', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (285, '55487', 'Minneapolis', 'MN');
insert into city (city_ID, zip, city_name, state) values (286, '79764', 'Odessa', 'TX');
insert into city (city_ID, zip, city_name, state) values (287, '27610', 'Raleigh', 'NC');
insert into city (city_ID, zip, city_name, state) values (288, '90398', 'Inglewood', 'CA');
insert into city (city_ID, zip, city_name, state) values (289, '95064', 'Santa Cruz', 'CA');
insert into city (city_ID, zip, city_name, state) values (290, '27150', 'Winston Salem', 'NC');
insert into city (city_ID, zip, city_name, state) values (291, '72118', 'North Little Rock', 'AR');
insert into city (city_ID, zip, city_name, state) values (292, '92424', 'San Bernardino', 'CA');
insert into city (city_ID, zip, city_name, state) values (293, '17126', 'Harrisburg', 'PA');
insert into city (city_ID, zip, city_name, state) values (294, '31998', 'Columbus', 'GA');
insert into city (city_ID, zip, city_name, state) values (295, '94807', 'Richmond', 'CA');
insert into city (city_ID, zip, city_name, state) values (296, '91505', 'Burbank', 'CA');
insert into city (city_ID, zip, city_name, state) values (297, '92883', 'Corona', 'CA');
insert into city (city_ID, zip, city_name, state) values (298, '45243', 'Cincinnati', 'OH');
insert into city (city_ID, zip, city_name, state) values (299, '10079', 'New York City', 'NY');
insert into city (city_ID, zip, city_name, state) values (300, '80150', 'Englewood', 'CO');
insert into city (city_ID, zip, city_name, state) values (301, '08650', 'Trenton', 'NJ');
insert into city (city_ID, zip, city_name, state) values (302, '02298', 'Boston', 'MA');
insert into city (city_ID, zip, city_name, state) values (303, '70165', 'New Orleans', 'LA');
insert into city (city_ID, zip, city_name, state) values (304, '21203', 'Baltimore', 'MD');
insert into city (city_ID, zip, city_name, state) values (305, '22093', 'Ashburn', 'VA');
insert into city (city_ID, zip, city_name, state) values (306, '78215', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (307, '12255', 'Albany', 'NY');
insert into city (city_ID, zip, city_name, state) values (308, '33023', 'Hollywood', 'FL');
insert into city (city_ID, zip, city_name, state) values (309, '55487', 'Minneapolis', 'MN');
insert into city (city_ID, zip, city_name, state) values (310, '14233', 'Buffalo', 'NY');
insert into city (city_ID, zip, city_name, state) values (311, '75221', 'Dallas', 'TX');
insert into city (city_ID, zip, city_name, state) values (312, '91406', 'Van Nuys', 'CA');
insert into city (city_ID, zip, city_name, state) values (313, '06922', 'Stamford', 'CT');
insert into city (city_ID, zip, city_name, state) values (314, '27150', 'Winston Salem', 'NC');
insert into city (city_ID, zip, city_name, state) values (315, '10029', 'New York City', 'NY');
insert into city (city_ID, zip, city_name, state) values (316, '34643', 'Largo', 'FL');
insert into city (city_ID, zip, city_name, state) values (317, '47732', 'Evansville', 'IN');
insert into city (city_ID, zip, city_name, state) values (318, '99215', 'Spokane', 'WA');
insert into city (city_ID, zip, city_name, state) values (319, '66642', 'Topeka', 'KS');
insert into city (city_ID, zip, city_name, state) values (320, '34233', 'Sarasota', 'FL');
insert into city (city_ID, zip, city_name, state) values (321, '20409', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (322, '23668', 'Hampton', 'VA');
insert into city (city_ID, zip, city_name, state) values (323, '01654', 'Worcester', 'MA');
insert into city (city_ID, zip, city_name, state) values (324, '78260', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (325, '10014', 'New York City', 'NY');
insert into city (city_ID, zip, city_name, state) values (326, '31904', 'Columbus', 'GA');
insert into city (city_ID, zip, city_name, state) values (327, '32854', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (328, '77212', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (329, '61635', 'Peoria', 'IL');
insert into city (city_ID, zip, city_name, state) values (330, '92668', 'Orange', 'CA');
insert into city (city_ID, zip, city_name, state) values (331, '55487', 'Minneapolis', 'MN');
insert into city (city_ID, zip, city_name, state) values (332, '20551', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (333, '33185', 'Miami', 'FL');
insert into city (city_ID, zip, city_name, state) values (334, '43268', 'Columbus', 'OH');
insert into city (city_ID, zip, city_name, state) values (335, '33028', 'Hollywood', 'FL');
insert into city (city_ID, zip, city_name, state) values (336, '78682', 'Round Rock', 'TX');
insert into city (city_ID, zip, city_name, state) values (337, '48224', 'Detroit', 'MI');
insert into city (city_ID, zip, city_name, state) values (338, '20041', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (339, '77080', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (340, '55480', 'Minneapolis', 'MN');
insert into city (city_ID, zip, city_name, state) values (341, '32803', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (342, '20205', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (343, '90310', 'Inglewood', 'CA');
insert into city (city_ID, zip, city_name, state) values (344, '28225', 'Charlotte', 'NC');
insert into city (city_ID, zip, city_name, state) values (345, '78044', 'Laredo', 'TX');
insert into city (city_ID, zip, city_name, state) values (346, '23663', 'Hampton', 'VA');
insert into city (city_ID, zip, city_name, state) values (347, '48912', 'Lansing', 'MI');
insert into city (city_ID, zip, city_name, state) values (348, '85284', 'Tempe', 'AZ');
insert into city (city_ID, zip, city_name, state) values (349, '31296', 'Macon', 'GA');
insert into city (city_ID, zip, city_name, state) values (350, '98481', 'Tacoma', 'WA');
insert into city (city_ID, zip, city_name, state) values (351, '23277', 'Richmond', 'VA');
insert into city (city_ID, zip, city_name, state) values (352, '40510', 'Lexington', 'KY');
insert into city (city_ID, zip, city_name, state) values (353, '46202', 'Indianapolis', 'IN');
insert into city (city_ID, zip, city_name, state) values (354, '92648', 'Huntington Beach', 'CA');
insert into city (city_ID, zip, city_name, state) values (355, '33336', 'Fort Lauderdale', 'FL');
insert into city (city_ID, zip, city_name, state) values (356, '29203', 'Columbia', 'SC');
insert into city (city_ID, zip, city_name, state) values (357, '38197', 'Memphis', 'TN');
insert into city (city_ID, zip, city_name, state) values (358, '10305', 'Staten Island', 'NY');
insert into city (city_ID, zip, city_name, state) values (359, '38188', 'Memphis', 'TN');
insert into city (city_ID, zip, city_name, state) values (360, '77095', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (361, '89519', 'Reno', 'NV');
insert into city (city_ID, zip, city_name, state) values (362, '32819', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (363, '72222', 'Little Rock', 'AR');
insert into city (city_ID, zip, city_name, state) values (364, '30306', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (365, '20816', 'Bethesda', 'MD');
insert into city (city_ID, zip, city_name, state) values (366, '84199', 'Salt Lake City', 'UT');
insert into city (city_ID, zip, city_name, state) values (367, '15286', 'Pittsburgh', 'PA');
insert into city (city_ID, zip, city_name, state) values (368, '55448', 'Minneapolis', 'MN');
insert into city (city_ID, zip, city_name, state) values (369, '98907', 'Yakima', 'WA');
insert into city (city_ID, zip, city_name, state) values (370, '95150', 'San Jose', 'CA');
insert into city (city_ID, zip, city_name, state) values (371, '70820', 'Baton Rouge', 'LA');
insert into city (city_ID, zip, city_name, state) values (372, '99260', 'Spokane', 'WA');
insert into city (city_ID, zip, city_name, state) values (373, '47937', 'Crawfordsville', 'IN');
insert into city (city_ID, zip, city_name, state) values (374, '33884', 'Winter Haven', 'FL');
insert into city (city_ID, zip, city_name, state) values (375, '26505', 'Morgantown', 'WV');
insert into city (city_ID, zip, city_name, state) values (376, '12205', 'Albany', 'NY');
insert into city (city_ID, zip, city_name, state) values (377, '85297', 'Gilbert', 'AZ');
insert into city (city_ID, zip, city_name, state) values (378, '76310', 'Wichita Falls', 'TX');
insert into city (city_ID, zip, city_name, state) values (379, '78783', 'Austin', 'TX');
insert into city (city_ID, zip, city_name, state) values (380, '67215', 'Wichita', 'KS');
insert into city (city_ID, zip, city_name, state) values (381, '15205', 'Pittsburgh', 'PA');
insert into city (city_ID, zip, city_name, state) values (382, '64504', 'Saint Joseph', 'MO');
insert into city (city_ID, zip, city_name, state) values (383, '66667', 'Topeka', 'KS');
insert into city (city_ID, zip, city_name, state) values (384, '79764', 'Odessa', 'TX');
insert into city (city_ID, zip, city_name, state) values (385, '94207', 'Sacramento', 'CA');
insert into city (city_ID, zip, city_name, state) values (386, '94660', 'Oakland', 'CA');
insert into city (city_ID, zip, city_name, state) values (387, '20546', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (388, '06606', 'Bridgeport', 'CT');
insert into city (city_ID, zip, city_name, state) values (389, '33411', 'West Palm Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (390, '07112', 'Newark', 'NJ');
insert into city (city_ID, zip, city_name, state) values (391, '10060', 'New York City', 'NY');
insert into city (city_ID, zip, city_name, state) values (392, '77218', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (393, '18763', 'Wilkes Barre', 'PA');
insert into city (city_ID, zip, city_name, state) values (394, '33411', 'West Palm Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (395, '77065', 'Houston', 'TX');
insert into city (city_ID, zip, city_name, state) values (396, '06538', 'New Haven', 'CT');
insert into city (city_ID, zip, city_name, state) values (397, '28805', 'Asheville', 'NC');
insert into city (city_ID, zip, city_name, state) values (398, '55573', 'Young America', 'MN');
insert into city (city_ID, zip, city_name, state) values (399, '33448', 'Delray Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (400, '07505', 'Paterson', 'NJ');
insert into city (city_ID, zip, city_name, state) values (401, '78260', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (402, '93399', 'Bakersfield', 'CA');
insert into city (city_ID, zip, city_name, state) values (403, '28230', 'Charlotte', 'NC');
insert into city (city_ID, zip, city_name, state) values (404, '30061', 'Marietta', 'GA');
insert into city (city_ID, zip, city_name, state) values (405, '06510', 'New Haven', 'CT');
insert into city (city_ID, zip, city_name, state) values (406, '94147', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (407, '78759', 'Austin', 'TX');
insert into city (city_ID, zip, city_name, state) values (408, '73109', 'Oklahoma City', 'OK');
insert into city (city_ID, zip, city_name, state) values (409, '33190', 'Miami', 'FL');
insert into city (city_ID, zip, city_name, state) values (410, '94250', 'Sacramento', 'CA');
insert into city (city_ID, zip, city_name, state) values (411, '37240', 'Nashville', 'TN');
insert into city (city_ID, zip, city_name, state) values (412, '48258', 'Detroit', 'MI');
insert into city (city_ID, zip, city_name, state) values (413, '17140', 'Harrisburg', 'PA');
insert into city (city_ID, zip, city_name, state) values (414, '47705', 'Evansville', 'IN');
insert into city (city_ID, zip, city_name, state) values (415, '55402', 'Minneapolis', 'MN');
insert into city (city_ID, zip, city_name, state) values (416, '19886', 'Wilmington', 'DE');
insert into city (city_ID, zip, city_name, state) values (417, '27705', 'Durham', 'NC');
insert into city (city_ID, zip, city_name, state) values (418, '78465', 'Corpus Christi', 'TX');
insert into city (city_ID, zip, city_name, state) values (419, '59112', 'Billings', 'MT');
insert into city (city_ID, zip, city_name, state) values (420, '25770', 'Huntington', 'WV');
insert into city (city_ID, zip, city_name, state) values (421, '94522', 'Concord', 'CA');
insert into city (city_ID, zip, city_name, state) values (422, '37931', 'Knoxville', 'TN');
insert into city (city_ID, zip, city_name, state) values (423, '30351', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (424, '79999', 'El Paso', 'TX');
insert into city (city_ID, zip, city_name, state) values (425, '45505', 'Springfield', 'OH');
insert into city (city_ID, zip, city_name, state) values (426, '59806', 'Missoula', 'MT');
insert into city (city_ID, zip, city_name, state) values (427, '36616', 'Mobile', 'AL');
insert into city (city_ID, zip, city_name, state) values (428, '75241', 'Dallas', 'TX');
insert into city (city_ID, zip, city_name, state) values (429, '27264', 'High Point', 'NC');
insert into city (city_ID, zip, city_name, state) values (430, '06854', 'Norwalk', 'CT');
insert into city (city_ID, zip, city_name, state) values (431, '79968', 'El Paso', 'TX');
insert into city (city_ID, zip, city_name, state) values (432, '32255', 'Jacksonville', 'FL');
insert into city (city_ID, zip, city_name, state) values (433, '06726', 'Waterbury', 'CT');
insert into city (city_ID, zip, city_name, state) values (434, '31416', 'Savannah', 'GA');
insert into city (city_ID, zip, city_name, state) values (435, '01105', 'Springfield', 'MA');
insert into city (city_ID, zip, city_name, state) values (436, '53215', 'Milwaukee', 'WI');
insert into city (city_ID, zip, city_name, state) values (437, '91406', 'Van Nuys', 'CA');
insert into city (city_ID, zip, city_name, state) values (438, '31605', 'Valdosta', 'GA');
insert into city (city_ID, zip, city_name, state) values (439, '22111', 'Manassas', 'VA');
insert into city (city_ID, zip, city_name, state) values (440, '10004', 'New York City', 'NY');
insert into city (city_ID, zip, city_name, state) values (441, '64504', 'Saint Joseph', 'MO');
insert into city (city_ID, zip, city_name, state) values (442, '63121', 'Saint Louis', 'MO');
insert into city (city_ID, zip, city_name, state) values (443, '84409', 'Ogden', 'UT');
insert into city (city_ID, zip, city_name, state) values (444, '20456', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (445, '46862', 'Fort Wayne', 'IN');
insert into city (city_ID, zip, city_name, state) values (446, '75372', 'Dallas', 'TX');
insert into city (city_ID, zip, city_name, state) values (447, '46867', 'Fort Wayne', 'IN');
insert into city (city_ID, zip, city_name, state) values (448, '59112', 'Billings', 'MT');
insert into city (city_ID, zip, city_name, state) values (449, '30316', 'Atlanta', 'GA');
insert into city (city_ID, zip, city_name, state) values (450, '95210', 'Stockton', 'CA');
insert into city (city_ID, zip, city_name, state) values (451, '40576', 'Lexington', 'KY');
insert into city (city_ID, zip, city_name, state) values (452, '47732', 'Evansville', 'IN');
insert into city (city_ID, zip, city_name, state) values (453, '79699', 'Abilene', 'TX');
insert into city (city_ID, zip, city_name, state) values (454, '76905', 'San Angelo', 'TX');
insert into city (city_ID, zip, city_name, state) values (455, '20709', 'Laurel', 'MD');
insert into city (city_ID, zip, city_name, state) values (456, '06140', 'Hartford', 'CT');
insert into city (city_ID, zip, city_name, state) values (457, '87180', 'Albuquerque', 'NM');
insert into city (city_ID, zip, city_name, state) values (458, '96154', 'South Lake Tahoe', 'CA');
insert into city (city_ID, zip, city_name, state) values (459, '94137', 'San Francisco', 'CA');
insert into city (city_ID, zip, city_name, state) values (460, '75251', 'Dallas', 'TX');
insert into city (city_ID, zip, city_name, state) values (461, '33543', 'Zephyrhills', 'FL');
insert into city (city_ID, zip, city_name, state) values (462, '75205', 'Dallas', 'TX');
insert into city (city_ID, zip, city_name, state) values (463, '94230', 'Sacramento', 'CA');
insert into city (city_ID, zip, city_name, state) values (464, '02114', 'Boston', 'MA');
insert into city (city_ID, zip, city_name, state) values (465, '28410', 'Wilmington', 'NC');
insert into city (city_ID, zip, city_name, state) values (466, '37665', 'Kingsport', 'TN');
insert into city (city_ID, zip, city_name, state) values (467, '90505', 'Torrance', 'CA');
insert into city (city_ID, zip, city_name, state) values (468, '91109', 'Pasadena', 'CA');
insert into city (city_ID, zip, city_name, state) values (469, '99812', 'Juneau', 'AK');
insert into city (city_ID, zip, city_name, state) values (470, '20557', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (471, '96845', 'Honolulu', 'HI');
insert into city (city_ID, zip, city_name, state) values (472, '33069', 'Pompano Beach', 'FL');
insert into city (city_ID, zip, city_name, state) values (473, '78278', 'San Antonio', 'TX');
insert into city (city_ID, zip, city_name, state) values (474, '71166', 'Shreveport', 'LA');
insert into city (city_ID, zip, city_name, state) values (475, '22333', 'Alexandria', 'VA');
insert into city (city_ID, zip, city_name, state) values (476, '22111', 'Manassas', 'VA');
insert into city (city_ID, zip, city_name, state) values (477, '62776', 'Springfield', 'IL');
insert into city (city_ID, zip, city_name, state) values (478, '33694', 'Tampa', 'FL');
insert into city (city_ID, zip, city_name, state) values (479, '58207', 'Grand Forks', 'ND');
insert into city (city_ID, zip, city_name, state) values (480, '33330', 'Fort Lauderdale', 'FL');
insert into city (city_ID, zip, city_name, state) values (481, '45203', 'Cincinnati', 'OH');
insert into city (city_ID, zip, city_name, state) values (482, '76905', 'San Angelo', 'TX');
insert into city (city_ID, zip, city_name, state) values (483, '93740', 'Fresno', 'CA');
insert into city (city_ID, zip, city_name, state) values (484, '32885', 'Orlando', 'FL');
insert into city (city_ID, zip, city_name, state) values (485, '33715', 'Saint Petersburg', 'FL');
insert into city (city_ID, zip, city_name, state) values (486, '28305', 'Fayetteville', 'NC');
insert into city (city_ID, zip, city_name, state) values (487, '06825', 'Fairfield', 'CT');
insert into city (city_ID, zip, city_name, state) values (488, '77493', 'Katy', 'TX');
insert into city (city_ID, zip, city_name, state) values (489, '90010', 'Los Angeles', 'CA');
insert into city (city_ID, zip, city_name, state) values (490, '91328', 'Northridge', 'CA');
insert into city (city_ID, zip, city_name, state) values (491, '77505', 'Pasadena', 'TX');
insert into city (city_ID, zip, city_name, state) values (492, '71307', 'Alexandria', 'LA');
insert into city (city_ID, zip, city_name, state) values (493, '21211', 'Baltimore', 'MD');
insert into city (city_ID, zip, city_name, state) values (494, '04109', 'Portland', 'ME');
insert into city (city_ID, zip, city_name, state) values (495, '48275', 'Detroit', 'MI');
insert into city (city_ID, zip, city_name, state) values (496, '20010', 'Washington', 'DC');
insert into city (city_ID, zip, city_name, state) values (497, '45403', 'Dayton', 'OH');
insert into city (city_ID, zip, city_name, state) values (498, '31416', 'Savannah', 'GA');
insert into city (city_ID, zip, city_name, state) values (499, '02124', 'Boston', 'MA');
insert into city (city_ID, zip, city_name, state) values (500, '87110', 'Albuquerque', 'NM');
